/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package form;

import java.awt.Color;
import java.awt.Font;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import javax.swing.ImageIcon;
import swing.ScrollBarr;
import utils.linkData;

/**
 *
 * @author TRONG NGHIA
 */
public class FormDetailMusic extends javax.swing.JPanel {

    /**
     * Creates new form FormDetailMusic
     */
    public FormDetailMusic() {
        initComponents();
        fileTxt();
//        loadAnh();
        content.setVerticalScrollBar(new ScrollBarr());
        content.setBackground(new Color(29, 38, 49));
        fileTxtMota();
        lbMoTa.setForeground(Color.WHITE);
        jLabel4.setForeground(Color.WHITE);
    }

    void fileTxt() {
        String linkBH = linkData.getLinkBH();
        String linkAnh = linkData.getLinkAnh();
        String tenBaiHat = linkData.getTenBH();
        String caSi = linkData.getCaSi();
        System.out.println("link anh bai hat" + linkAnh);
//        String path = "D:\\loinho.txt"; 
        String absolutePath = new File(linkBH).getAbsolutePath();
        try {
            //tạo đối tượng file  
            File file = new File(absolutePath);
            //kiểm tra xem file có tồn tại hay không
            if (file.exists()) {
                //tạo đối tượng filereader và BufferedReader
                FileReader filereder = new FileReader(file);
                BufferedReader bufferedReader = new BufferedReader(filereder);
                //đọc nội dung từ file
                StringBuffer content = new StringBuffer();
                String line;
                while ((line = bufferedReader.readLine()) != null) {
                    content.append(line);
                    content.append("<br>");
                }
                bufferedReader.close();
                filereder.close();
                lbInNhac.setText("<html>" + content.toString() + "</html");
                lbInNhac.setFont(new Font("Arial", Font.BOLD, 20) {
                });
                //in ảnh lên lable
                lbInNhac.setForeground(Color.white);
                lbTenBH.setText(tenBaiHat);
                lbCaSi.setText(caSi);
                ImageIcon icon = new ImageIcon(getClass().getResource(linkAnh));
                lbIcon.setIcon(icon);
                lbIcon.getToolTipText();
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    //txt mota
    void fileTxtMota() {
        String linkMt = linkData.getMota();
//        String path = "D:\\loinho.txt"; 
        String absolutePath = new File(linkMt).getAbsolutePath();
        try {
            //tạo đối tượng file  
            File file = new File(absolutePath);
            //kiểm tra xem file có tồn tại hay không
            if (file.exists()) {
                //tạo đối tượng filereader và BufferedReader
                FileReader filereder = new FileReader(file);
                BufferedReader bufferedReader = new BufferedReader(filereder);
                //đọc nội dung từ file
                StringBuffer content = new StringBuffer();
                String line;
                while ((line = bufferedReader.readLine()) != null) {
                    content.append(line);
                    content.append("<br>");
                }
                bufferedReader.close();
                filereder.close();
                lbMoTa.setText("<html>" + content.toString() + "</html");
                lbMoTa.setFont(new Font("Arial", Font.PLAIN, 12) {
                });
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbIcon = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lbTenBH = new javax.swing.JLabel();
        imageAvarta1 = new swing.ImageAvarta();
        lbCaSi = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lbMoTa = new javax.swing.JLabel();
        content = new javax.swing.JScrollPane();
        lbInNhac = new javax.swing.JLabel();

        setBackground(new java.awt.Color(29, 38, 49));

        lbIcon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel1.setBackground(new java.awt.Color(29, 38, 49));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setText("Bài hát:");
        jLabel1.setOpaque(true);

        lbTenBH.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        lbTenBH.setForeground(new java.awt.Color(255, 255, 255));

        lbCaSi.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        lbCaSi.setForeground(new java.awt.Color(255, 255, 255));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("1.00.000.000 lượt nghe");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 204, 204));
        jLabel5.setText("02/12/2004");

        content.setBackground(new java.awt.Color(29, 38, 49));
        content.setBorder(null);
        content.setForeground(new java.awt.Color(29, 38, 49));
        content.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        content.setHorizontalScrollBar(null);

        lbInNhac.setBackground(new java.awt.Color(29, 38, 49));
        lbInNhac.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        content.setViewportView(lbInNhac);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(lbIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(imageAvarta1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(12, 12, 12)
                            .addComponent(lbCaSi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(lbTenBH, javax.swing.GroupLayout.PREFERRED_SIZE, 563, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(lbMoTa, javax.swing.GroupLayout.PREFERRED_SIZE, 644, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(content)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(lbTenBH, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(5, 5, 5)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(imageAvarta1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(lbCaSi, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(5, 5, 5)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addGap(12, 12, 12)
                        .addComponent(lbMoTa, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lbIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(content, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane content;
    private swing.ImageAvarta imageAvarta1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lbCaSi;
    private javax.swing.JLabel lbIcon;
    private javax.swing.JLabel lbInNhac;
    private javax.swing.JLabel lbMoTa;
    private javax.swing.JLabel lbTenBH;
    // End of variables declaration//GEN-END:variables
}
