/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package form;

import dao.NguoiDungDangKyDAO;
import dao.*;
import entity.AccountData;
import entity.NguoiDung;
import entity.TaiKhoan;
import java.awt.Color;
import java.io.File;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.Timer;
import main.Main;
import utils.*;

/**
 *
 * @author PC
 */
public class updateAnh extends javax.swing.JFrame {

    /**
     * Creates new form updateAnh
     */
    public updateAnh() {
        initComponents();
        this.btnOk.setEnabled(false);
        setLocationRelativeTo(null);
        this.lbLoading.setVisible(false);
    }
    TaiKhoanDAO tkdao = new TaiKhoanDAO();
    JFileChooser filechooser = new JFileChooser();
    Signup sg = new Signup();
    File file;
    File file2;

    void chonAnh() {
        if (filechooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            file = filechooser.getSelectedFile();
            System.out.println("" + file);
            String imagePath = file.getAbsolutePath();
            System.out.println("" + imagePath);
            AccountData.setLink(imagePath);
            XImage.save(file);
            int setwith = 250;
            int setHeight = 300;
            ImageIcon icon = XImage.read(file.getName(), setwith, setHeight);
            lbAnh.setIcon(icon);
            lbAnh.setToolTipText(file.getName());
            lbAnh.setText("");
        }
    }

    TaiKhoan getForm() {
        TaiKhoan tk = new TaiKhoan();
        tk.setTenTk(AccountData.getTenTK());
        tk.setAvatar(file.getAbsolutePath());
        return tk;
    }

    TaiKhoan getForm2() {
        String path = "C:\\Users\\PC\\Desktop\\Music-M6-master\\src\\main\\resources\\icon\\AnhMatDinh.png";
        file2 = new File(path);
        TaiKhoan tk = new TaiKhoan();
        tk.setTenTk(AccountData.getTenTK());
        tk.setAvatar(file2.getAbsolutePath());
        return tk;
    }

    void update() {
        if (lbAnh != null) {
            btnOk.setEnabled(true);
        }
    }

    void ok() {
        TaiKhoan tk = getForm();
        try {
            tkdao.update(tk);
            msgBox.alert(this, "Thêm ảnh thành công");
            lbLoading.setVisible(true);
            Timer formTimer = new Timer(2000, event -> {
                // Chuyển đến form chính sau 2 giây
                LogIn li = new LogIn();
                li.setVisible(true);
                this.dispose();
            });
            formTimer.setRepeats(false);
            formTimer.start();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    void boQua() {
        TaiKhoan tk =getForm2();
        try {
            tkdao.update(tk);
            lbLoading.setVisible(true);
            Timer formTimer = new Timer(2000, event -> {
                // Chuyển đến form chính sau 2 giây
                LogIn li = new LogIn();
                li.setVisible(true);
                this.dispose();
            });
            formTimer.setRepeats(false);
            formTimer.start();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbLoading = new javax.swing.JLabel();
        lbAnh = new javax.swing.JLabel();
        btnOk = new swing.Button();
        btnBoQua = new swing.Button();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbLoading.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/loading.gif"))); // NOI18N
        getContentPane().add(lbLoading, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 180, -1, -1));

        lbAnh.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbAnh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/AnhMatDinh.png"))); // NOI18N
        lbAnh.setText("Ảnh");
        lbAnh.setToolTipText("");
        lbAnh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbAnhMouseClicked(evt);
            }
        });
        getContentPane().add(lbAnh, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 60, 220, 260));

        btnOk.setText("Ok");
        btnOk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnOkMouseClicked(evt);
            }
        });
        btnOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkActionPerformed(evt);
            }
        });
        getContentPane().add(btnOk, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 330, 220, 30));

        btnBoQua.setText("Bỏ qua");
        btnBoQua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBoQuaActionPerformed(evt);
            }
        });
        getContentPane().add(btnBoQua, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 370, 220, 30));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Thêm ảnh đại diện");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 30, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/bgUpdateAnh.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lbAnhMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbAnhMouseClicked
        update();
        chonAnh();
    }//GEN-LAST:event_lbAnhMouseClicked

    private void btnOkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnOkMouseClicked
        ok();
    }//GEN-LAST:event_btnOkMouseClicked

    private void btnBoQuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBoQuaActionPerformed
        boQua();
    }//GEN-LAST:event_btnBoQuaActionPerformed

    private void btnOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkActionPerformed
        boQua();
    }//GEN-LAST:event_btnOkActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(updateAnh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(updateAnh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(updateAnh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(updateAnh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new updateAnh().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private swing.Button btnBoQua;
    private swing.Button btnOk;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lbAnh;
    private javax.swing.JLabel lbLoading;
    // End of variables declaration//GEN-END:variables
}
